[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "8oJLsdGcukkSvFor38wbJvkU3UUgGhsuadHSGJHW4PtZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/fernando/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
